---
- name: Playbook to copy files
  become: yes
  hosts: localhost

  tasks:
   - name: inventory file
     template:
       src: ~/ansible-roles/roles/aws_ec2.yaml
       dest: ~/
       owner: root
       group: root
       remote_src: yes
       mode: 0755 
   - name: config file
     template:
       src: ~/ansible-roles/roles/ansible.cfg
       dest: ~/
       owner: root
       group: root
       remote_src: yes
       mode: 0755    
          