- name: unarchive prometheus repo
  unarchive: 
    src: https://github.com/prometheus/prometheus/releases/download/v2.38.0/prometheus-2.38.0.linux-amd64.tar.gz  
    dest: /tmp
    remote_src: yes
    validate_certs: no
- name: Copy prometheus file to bin
  copy:
    src: /root/prometheus-2.38.0.linux-amd64/prometheus
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
- name: Copy prometheus config file
  template:
    src: ~/ansible/roles/prometheus.yml
    dest: /root/prometheus-2.38.0.linux-amd64
    remote_src: yes
    mode: 0755    
- name: prometheus args
  template:
    src: ~/ansible-roles/roles/prometheus/templates/prometheus.service.j2
    dest: /etc/default/prometheus.service
    mode: 0644
    owner: root
    group: root
  notify: restart_prometheus
- name: prometheus configuration file
  template:
    src: ~/ansible-roles/roles/prometheus/templates/prometheus.yml.j2
    dest: "{{ prometheus_dir_configuration }}/prometheus.yml"
    mode: 0755
    owner: prometheus
    group: prometheus
  notify: reload_prometheus
- name: start prometheus
  systemd:
    name: prometheus
    state: started
    enabled: yes
